language: java
jdk:
  - oraclejdk8
sudo: false
install: true
addons:
  sonarcloud:
    organization: "ut-graphtereffects"
    token:
      secure: "umuUq2WFz6Iw6U1HnC/0ibeHFJtKxlXQC3xzDLgzu11oRbr+sMFmX83g+B8UTLHobv7zywjDSNjageIk1ThjwPI4s90BoK9saB1W5d6bu1v9G/JD5L0TTKRhg1AmS8eazmLJ3qiatglgzatr6U3/vy9NadgOn9arQIpI1Erh27VSDaPfWs8M7Isnjenezc6VvWUKeLqYxXCmNIOjHan/HEtwHPBTndtHzfwKIzv7GGe3pyNPHgBhTt/9SO6Bf+bgU/WHF7ErQlv9Bdmpi7qFK6lEO/tQltU6K8T7fNXNkNMThdLibZUXwVNrgQ7TOLV08bXbb7ztWlgrnCdmBon8Rq6uqoum7GEHzo3sXyUzZ+H6PyCodU/cJ6nCtoZRxZVwvF7vHChdhKpmliRdG12SEU6xQNsuOBk5qnn+L+iO7QbL6VoesJ1FVt9c/CWNDJe7EqorSSJY9eTVErQC/RSvkcrZmDSjtCoc9UB5PrklTd2teF48qTOn3qnenkO8JqlkIWBqRXhK2op3wz//adWzbor0ZEIlAIJzG/yP8XbD+Y/CJlVN7gsZNY7+FTZtmG3iHvfGApXlhmQOJslcE7YoREEai/nm5FFHshqe+qnp/8KW8a0RVrA+hJLwm8nPnDiWVhwhXHG/nhwjYJ5VP/+pDAh3NUB7R8yalai6lXUj5Us="
notifications:
  email:
    - s2021749@student.utwente.nl
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
