language: java
jdk:
  - oraclejdk8
sudo: false
install: true
addons:
  sonarcloud:
    organization: "grapthereffectspppp"
    token:
      secure: "5z6D36Lbtm9RhgmoPXPp+e3zucsYxBdDxp44DCsQ023nPoiTGdc2mxwLeiq65C2RyHw1jA9K9gnJ3wNc77jF2Wo7g1HSNE0Z3YmQM6zXvsad9uQn+ieAC5PSlN5gUUZLZH9Ji/VpSV4mJtOmh/HfKXb4fuW28iZ/WPbOvScPcLzzlPqADqGB8C54DKF52Vmw2DIAl/cDkYcnrSN8iG9MitSzyeK1t4HveANePMq8xu296m2N2YZVriRLhOXwpHn8cKARWAUhqNcL0QjbTZpQbRFZ1yXpDetLf9TPwBJfTQd7euS5qA2GL2Apa/T16NOjQltjHrVVvc8mFRSocGVXvGJL+IpQLR6LBq1aPmSQeXzFyNKJ/CIt0TA1qmDRJ+oUUqs73iUn8qmxBTTsOeoyIZNYtU9QTDyqAqxVSkFz4hmfemVqvItlt9i8T/RC53lYG5iODSdrqr1Xqio+dUoMIU8liqY4ya6IQenOEsJ/ZwlK9NZLb3iosoqIrjzk7jLOaThtJpwK7UnQpz78ioESJ7iVZ5czQu+epY23q+7/T9pNmNlsHst1bK+AJXbxuB3LUXv8GXY50k029odrE0uhhzsl8zxA7895sndICQYzOFO8QSAl18iWr9SIWu5nLRQfUFOIk/Yrb8UztflpIObfdAZivmZVCT+3i6cLQLvaOJw="
notifications:
  email:
    - s2021749@student.utwente.nl
script:
  - rm -rf $HOME/.sonar/cache
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
